pip3 install Flask-Session
pip3 install wtforms
pip3 install flask_wtf
pip3 install flask-login 
pip3 install gevent
pip3 install gevent-websocket
pip3 install flask-io
pip3 install flask-socketio
pip3 install flask-restful